name: Corbt Blog
description: This blog is dedicated to programming, machine learning, and other topics that interest me.
url: http://corbt.com/blog
markdown: rdiscount
permalink: /:title.html
destination: ../../public/blog
exclude:
  - Rakefile
  - Gemfile
  - .gitignore
safe: false