source 'https://rubygems.org'

gem 'rails', '4.0.0'

gem 'pg'

gem 'sass-rails', '~> 4.0.0'
gem 'bootstrap-sass'
gem 'bourbon'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'

group :production do 
	gem 'unicorn'
end

group :development do 
	gem 'capistrano', require: false
	gem 'capistrano-ext', require: false
	gem 'capistrano-unicorn', require: false
	gem 'capistrano-remote-cache-with-project-root'#, require: false
end

# Static pages
gem 'high_voltage'

gem 'slim'
gem 'redcarpet'

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
